MODULE_TOPDIR = ../../..
MODNAME = ml.class

PGM = ml.classify

include $(MODULE_TOPDIR)/include/Make/Script.make

default: script

# $(ETC)/$(MODNAME)/$(PGM)/%: % | $(ETC)/$(MODNAME)/$(PGM)
# 	$(INSTALL) $< $@
# 
# $(ETC)/$(MODNAME)/$(PGM):
# 	$(MKDIR) $@